spring:
  application:
    name: utility_supervisor
telegram:
  bot:
    name: ${BOT_NAME}
    token: ${TELEGRAM_TOKEN}
    chat_ids: ${TELEGRAM_CHAT_IDS}
scheduling:
  enabled: ${SCHEDULING_ENABLED:false}
  cron:
    update-koltushi: "0 * * * * *"

